### ISSUE TITLE
Runtime error: Cannot find module

### ISSUE THREAD

**Issue by darylf** [vasilevich/sync-yarnlock-into-packagejson#7]
I get the below error when I simply run `syncyarnlock`. I'm using git-bash on Windows to run the command. Yarn v1.13.0. I'm not sure if I'm missing something.

```
$ syncyarnlock
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\yarn\lib\lockfile\wrapper'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at wrapper (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\yarn-lock-convert\index.js:10:12)
    at Object. (C:\Users\username\AppData\Local\Yarn\Data\global\node_modules\yarn-lock-convert\index.js:11:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

**Comment by vasilevich** [comment]
please make sure your yarn version is atleast 0.18.0 or higher.
in accordance with this:
https://github.com/numtide/yarnlock2json/blob/master/package.json

if still doesnt work let me know and we can check more throughly

**Comment by darylf** [comment]
As mentioned above, I'm using the latest stable yarn v1.13.0
